/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.SwingUtilities;

/**
 *
 * @author An
 */
public class GameModeMenuJPanel extends javax.swing.JPanel {

    private BufferedImage backgroundImage;
    
    public GameModeMenuJPanel() {
        try{
            backgroundImage = ImageIO.read(new File("src/image/bamboo.png"));
        }catch(IOException ex){
            System.out.println(ex.toString());
        }
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFunQuiz = new javax.swing.JButton();
        btnLogicalQuiz = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setName("Game Mode Menu JPanel"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFunQuiz.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnFunQuiz.setText("Câu Hỏi Vui");
        btnFunQuiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFunQuiz.setMaximumSize(new java.awt.Dimension(200, 40));
        btnFunQuiz.setMinimumSize(new java.awt.Dimension(200, 40));
        btnFunQuiz.setPreferredSize(new java.awt.Dimension(200, 40));
        btnFunQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFunQuizActionPerformed(evt);
            }
        });
        add(btnFunQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));
        btnFunQuiz.getAccessibleContext().setAccessibleName("");

        btnLogicalQuiz.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnLogicalQuiz.setText("Câu Hỏi Logic");
        btnLogicalQuiz.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogicalQuiz.setMaximumSize(new java.awt.Dimension(200, 40));
        btnLogicalQuiz.setMinimumSize(new java.awt.Dimension(200, 40));
        btnLogicalQuiz.setPreferredSize(new java.awt.Dimension(200, 40));
        add(btnLogicalQuiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        btnBack.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnBack.setText("Trở về");
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.setMaximumSize(new java.awt.Dimension(200, 40));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 40));
        btnBack.setPreferredSize(new java.awt.Dimension(200, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainFrame gameFrame = (MainFrame) SwingUtilities.getRoot(this);
        gameFrame.setContentPane(new StarMenuJPanel());
        gameFrame.validate();
        gameFrame.repaint();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnFunQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFunQuizActionPerformed
        MainFrame gameFrame = (MainFrame) SwingUtilities.getRoot(this);
        gameFrame.setContentPane(new GamePlayJPanel());
        gameFrame.validate();
        gameFrame.repaint();
    }//GEN-LAST:event_btnFunQuizActionPerformed

    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(backgroundImage, 0, 0, this);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnFunQuiz;
    private javax.swing.JButton btnLogicalQuiz;
    // End of variables declaration//GEN-END:variables
}
