/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package model;

import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.sound.sampled.Clip;
import javax.swing.SwingUtilities;

/**
 *
 * @author An
 */
public class SettingJPanel extends javax.swing.JPanel {
    
    private BufferedImage image;
    
    public SettingJPanel() {
         try{
            image = ImageIO.read(new File("src/image/autumn.png"));
        }catch(IOException ex){
            System.out.println(ex.toString());
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        btnSoundController = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnLogin.setText("Admin");
        btnLogin.setPreferredSize(new java.awt.Dimension(200, 40));
        add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        btnSoundController.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnSoundController.setText("Sound: OFF");
        btnSoundController.setPreferredSize(new java.awt.Dimension(200, 40));
        btnSoundController.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSoundControllerActionPerformed(evt);
            }
        });
        add(btnSoundController, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        btnBack.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        btnBack.setText("Trở về");
        btnBack.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBack.setMaximumSize(new java.awt.Dimension(200, 40));
        btnBack.setMinimumSize(new java.awt.Dimension(200, 40));
        btnBack.setPreferredSize(new java.awt.Dimension(200, 40));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSoundControllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSoundControllerActionPerformed
        if(MainFrame.clip.isRunning()){
            MainFrame.clip.stop();
            btnSoundController.setText(MainFrame.SOUND_ON);
        }else{
            MainFrame.clip.start();
            MainFrame.clip.loop(Clip.LOOP_CONTINUOUSLY);
            btnSoundController.setText(MainFrame.SOUND_OFF);
        }
    }//GEN-LAST:event_btnSoundControllerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        MainFrame gameFrame = (MainFrame) SwingUtilities.getRoot(this);
        gameFrame.setContentPane(new StarMenuJPanel());
        gameFrame.validate();
        gameFrame.repaint();
    }//GEN-LAST:event_btnBackActionPerformed
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(image, 0, 0, this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSoundController;
    // End of variables declaration//GEN-END:variables
}
